#include<iostream.h>
#include<conio.h>

class Numbers
{
	int num[10];
	public:
		Number()
		{
			for(int i=0;i<20;i++)
			{
				cout<<"\n Enter The Number : ";
				cin>>num[i];
			}
		}

		void Series()
		{
		}
};

void main()
{
	Number Odd,Even;
	int l;
	float len;

	cout<<"\n Enter 1.Even \n 2.Odd\n";

	switch(ch)
	{
		case 1 : cout<<"\n Enter The Number

			 Odd.Series();
			 break;

		case 2 : Even.Series();
			 break;
	}

	getch();
}